# Generated by Django 4.0 on 2024-11-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=15)),
                ('nombres', models.TextField(max_length=30)),
                ('lastnombre', models.TextField(max_length=30)),
                ('curso', models.TextField(max_length=20)),
                ('salon', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razon_ingreso', models.TextField()),
                ('estado_habil', models.TextField(choices=[('activo', 'activo'), ('desactivo', 'desactivo')], max_length=20)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('razon_egreso', models.TextField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categoria')),
                ('estado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estado_producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.proveedor')),
                ('rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
            ],
            options={
                'permissions': [('enable_producto', 'Puede activar producto'), ('disable_producto', 'Puede desactivar producto')],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=7)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('razon', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.producto')),
            ],
        ),
    ]
